routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','IndexController@index')->name('index');

Route::get('/demo','UsuarioController@lista');

Route::resource('almacen','AlmacenController');
Route::get('/almacenes/lista','AlmacenController@index')->name('almacenes.lista');

Route::resource('producto','ProductoController');
Route::get('/productos/lista','ProductoController@index')->name('productos.lista');

Route::resource('usuario','UsuarioController');
Route::get('/usuarios/lista','UsuarioController@index')->name('usuarios.lista');

Route::resource('registroEntrada','RegistroEntradaController');
Route::get('/registroentradas/lista','RegistroEntradaController@index')->name('registroentradas.lista');

Route::resource('registroSalida','RegistroSalidaController');
Route::get('/registrosalidas/lista','RegistroSalidaController@index')->name('registrosalidas.lista');

Route::get('/kardex/lista','KardexController@index')->name('kardex.lista');

Route::resource('existencia','ExistenciaController');
Route::get('/inventario/lista','InventarioController@index')->name('inventario.lista');
Route::get('/inventario/{almacen}','InventarioController@detalle');
Route::get('/inventario/exportar/{almacen}','InventarioController@exportar');

Route::get('/kardex/exportar/{lista}','KardexController@exportar');

Route::resource('documento','DocumentoController');
Route::resource('disposicion','DisposicionController');

Route::get('/login','LoginController@index')->name('login');
Route::post('/loginprocess','LoginController@validar')->name('logueo');
Route::get('/logout','LoginController@logout')->name('logout');
Route::get('/loginprocess','LoginController@index');

Route::resource('ticket','TicketController');
Route::get('/tickets/lista','TicketController@index')->name('tickets.lista');
Route::get('/ticketNotificado/{idnotificacion}','TicketController@showTicketNotificado');
Route::put('/ticketNotificado/{idnotificacion}','TicketController@updateTicketNotificado');

Route::get('/acercade/mostrar','HomeController@mostrar')->name('acercade.mostrar');
#Auth::routes();

app/Producto.php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model;

class Producto extends Model
{
    protected $primaryKey = 'idproducto';

    public function tipo(){
        return $this->belongsTo('App\Tipo','idtipo','idtipo');
    }

    public function unidadMedida(){
        return $this->belongsTo('App\UnidadMedida','idunidad','idunidad');
    }
}

app/Http/Controllers/ProductoController.php
<?php

namespace App\Http\Controllers;

use App\DetalleRegistroEntrada;
use App\DetalleRegistroSalida;
use App\Producto;
use App\RegistroEntrada;
use App\RegistroSalida;
use App\Tipo;
use App\Secuencia;
use App\UnidadMedida;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;


class ProductoController extends Controller
{
    public function __construct()
    {
        #VALIDAR QUE EL USUARIO ESTE AUTENTICADO
        $this->middleware('auth');
    }

    public function index()
    {
        #SE VALIDA EL ROL AUTORIZADO
        Auth::user()->authorizeRoles(['ALMACEN']);

        $productos=Producto::paginate(10);
        return view('producto.lista-producto',compact('productos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        #SE VALIDA EL ROL AUTORIZADO
        Auth::user()->authorizeRoles(['ALMACEN']);

        $tipos=Tipo::all();
        $unidades=UnidadMedida::all();
        return view('producto.crear-producto',compact('tipos'),compact('unidades'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        #SE VALIDA EL ROL AUTORIZADO
        Auth::user()->authorizeRoles(['ALMACEN']);

        $codigo=$request->get('txtCodigo');
        $descripcion=$request->get('txtDescripcion');
        $presentacion=$request->get('txtPresentacion');
        $idunidad=$request->get('txtUnidad');
        $idtipo=$request->get('txtTipo');

        #SI EXISTE UN PRODUCTO CON EL MISMO CODIGO ESTA DUPLICADO
        $productoBuscado=Producto::find($codigo);
        if($productoBuscado!=null){
            return back()->withErrors('El código '.$codigo." ya EXISTE, ingrese un código diferente");
        }

        #SI YA EXISTE UN ALMACEN , SE ENCUENTRA DUPLICADO
        $productoBuscado2=Producto::where('descripcion','=',$descripcion)->first();
        if($productoBuscado2!=null){
            return back()->withErrors('El producto '.$descripcion." ya EXISTE, ingrese un nombre de producto diferente");
        }

        $producto=new Producto();
        $producto->idproducto=$codigo;
        $producto->descripcion=$descripcion;
        $producto->presentacion=$presentacion;
        $producto->idunidad=(int)$idunidad;
        $producto->idtipo=(int)$idtipo;
        $producto->save();

        return redirect()->route('productos.lista');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Almacen  $almacen
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        #SE VALIDA EL ROL AUTORIZADO
        Auth::user()->authorizeRoles(['ALMACEN']);

        $producto=Producto::find($id);
        return view('producto.eliminar-producto',compact('producto'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Almacen  $almacen
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        #SE VALIDA EL ROL AUTORIZADO
        Auth::user()->authorizeRoles(['ALMACEN']);

        $tipos=Tipo::all();
        $unidades=UnidadMedida::all();
        $producto=Producto::find($id);

        #SI EXISTE UN PRODUCTO CON EL MISMO CODIGO ESTA DUPLICADO
        if($producto->atendido){
            return back()->withErrors('El ticket ya fue atendido, no se puede modificar');
        }


        return view('producto.editar-producto',['tipos'=>$tipos,'unidades'=>$unidades,'producto'=>$producto]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Almacen  $almacen
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        #SE VALIDA EL ROL AUTORIZADO
        Auth::user()->authorizeRoles(['ALMACEN']);

        $descripcion=$request->get('txtDescripcion');
        $concentracion=$request->get('txtConcentracion');
        $presentacion=$request->get('txtPresentacion');
        $idunidad=$request->get('txtUnidad');
        $idtipo=$request->get('txtTipo');

        $productoBuscado=Producto::find($id);
        $productoBuscado->descripcion=$descripcion;
        $productoBuscado->concentracion=$concentracion;
        $productoBuscado->presentacion=$presentacion;
        $productoBuscado->idtipo=(int)$idtipo;
        $productoBuscado->idunidad=(int)$idunidad;
        $productoBuscado->update();

        return redirect()->route('productos.lista');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Almacen  $almacen
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        #SE VALIDA EL ROL AUTORIZADO
        Auth::user()->authorizeRoles(['ALMACEN']);

        $productoBuscado=Producto::find($id);

        $entradas=RegistroEntrada::where('detalleRegistroEntradas.idproducto','=',$id)->get();


        if(count($entradas)>0){
            return back()->withErrors('El producto '.$productoBuscado->descripcion." tiene ingresos, imposible eliminar");
        }

        $salidas=RegistroSalida::where('detalleRegistroSalidas.idproducto','=',$id)->get();
        if(count($salidas)>0){
            return back()->withErrors('El producto '.$productoBuscado->descripcion." tiene salidas, imposible eliminar");
        }

        $productoBuscado->delete();

        return redirect()->route('productos.lista');
    }


}

resources/views/producto/crear-producto.blade.php
@extends('layouts.app')
@section('content')

   <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 subtitulo">
                Mantenimiento de Productos
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-2">
            </div>

            <div class="col-md-6 col-sm-12">
                <form class="needs-validation" action="{{action('ProductoController@store')}}" method="post" enctype="multipart/form-data" novalidate>
                    @csrf
                    <fieldset>
                        <legend class="sumario">Nuevo Producto</legend>
                        @if(count($errors)>0)
                                <!-- SI HUBIERA ERRORES SE MUESTRA UNA LISTA CON LOS ERRORES ENCONTRADOS   -->
                                <div class="alert alert-danger">
                                    <ul><!--SE REALIZA UN BUCLE PARA MOSTRAR LOS ERRORES -->
                                    @foreach($errors->all() as $error)
                                            <li>{{$error}}</li><!-- SE MUESTRA EL ERROR  -->
                                        @endforeach
                                    </ul>
                                </div>
                        @endif

                        <div class="form-group">
                            <label for="txtCodigo">Código</label>
                            <input type="text" class="form-control" id="txtCodigo" name="txtCodigo"  placeholder="Ingrese un Codigo" required autofocus maxlength="10">
                            <div class="invalid-feedback">
                                Por favor ingrese un Código con 10 caracteres como máximo.
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="txtDescripcion">Descripcion</label>
                            <input type="text" class="form-control" id="txtDescripcion" name="txtDescripcion"  placeholder="Ingrese una Descripcion" required autofocus maxlength="50">
                            <div class="invalid-feedback">
                                Por favor ingrese una Descripción con 50 caracteres como máximo.
                            </div>
                        </div>

                        <div class="row justify-content-center align-items-center">
                            <div class="col-md-5">
                                <div class="form-group ">
                                    <label for="txtUnidad">Unidad</label>
                                    <select class="form-control btn-light" id="txtUnidad" name="txtUnidad" >
                                        @foreach($unidades as $unidad)
                                            <option value={{$unidad->idunidad}}>{{$unidad->descripcion}} </option>
                                        @endforeach
                                    </select>
                                    <div class="invalid-feedback">
                                        Por favor seleccione una unidad
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-7">
                                <div class="form-group ">
                                    <label for="txtPresentacion">Presentación</label>
                                    <input type="text" class="form-control" id="txtPresentacion" name="txtPresentacion"  placeholder="Ingrese una Presentación" required autofocus maxlength="50">
                                    <div class="invalid-feedback">
                                        Por favor ingrese la presentación con 50 caracteres como máximo.
                                    </div>
                                </div>
                            </div>
                        </div>





                        <div class="form-group ">
                            <label for="txtTipo">Tipo</label>
                            <select class="form-control btn-light" id="txtTipo" name="txtTipo" >
                                @foreach($tipos as $tipo)
                                    <option value={{$tipo->idtipo}}>{{$tipo->descripcion}} </option>
                                @endforeach
                            </select>
                            <div class="invalid-feedback">
                                Por favor seleccione un tipo.
                            </div>
                        </div>

                        <!-- SI EL ROL TIENE PERMISOS PARA EDITAR -->
                        <button type="submit" class="btn btn-success">Registrar <i class="fas fa-save iconoBoton"></i></button>

                        <button type="button" class="btn btn-secondary float-right" onclick="window.location='{{ route("productos.lista") }}'">Cancelar <i class="fas fa-undo-alt iconoBoton"></i></button>
                    </fieldset>
                </form>
            </div>

            <div class="col-md-2">
            </div>
        </div>
    </div>


@endsection

resources/views/producto/editar-producto.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 subtitulo">
                Mantenimiento de Productos
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-2">
            </div>

            <div class="col-md-6 col-sm-12">
                <form class="needs-validation"  action="{{action('ProductoController@update',$producto->idproducto)}}" method="post" enctype="multipart/form-data" novalidate>
                    @csrf
                    {{ method_field('PUT') }}
                    <fieldset>

                        <legend class="sumario">Editar Producto</legend>
                         @if(count($errors)>0)
                        <!-- SI HUBIERA ERRORES SE MUESTRA UNA LISTA CON LOS ERRORES ENCONTRADOS   -->
                            <div class="alert alert-danger">
                                <ul><!--SE REALIZA UN BUCLE PARA MOSTRAR LOS ERRORES -->
                                    @foreach($errors->all() as $error)
                                        <li>{{$error}}</li><!-- SE MUESTRA EL ERROR  -->
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <div class="form-group">
                            <label for="txtCodigo">Código</label>
                            <input type="text" class="form-control" id="txtCodigo" name="txtCodigo"
                                   value="{{$producto->idproducto}}" placeholder="Ingrese un Codigo" readonly maxlength="10">
                            <div class="invalid-feedback">
                                Por favor ingrese un Código con 10 caracteres como máximo.
                            </div>
                        </div>

                        <div class="form-group ">
                            <label for="txtDescripcion">Descripcion</label>
                            <input type="text" class="form-control " id="txtDescripcion" name="txtDescripcion"
                                   value="{{$producto->descripcion}}" placeholder="Ingrese una Descripcion" required autofocus maxlength="50">
                            <div class="invalid-feedback">
                                Por favor ingrese una descripción con 50 caracteres como máximo.
                            </div>
                        </div>

                        <div class="row justify-content-center align-items-center">
                            <div class="col-md-5">
                                <div class="form-group ">
                                    <label for="txtUnidad">Unidad</label>
                                    <select class="form-control btn-light " id="txtUnidad" name="txtUnidad" >
                                        @foreach($unidades as $unidad)
                                            @if($unidad->idunidad==$producto->idunidad)
                                                <option value={{$unidad->idunidad}} selected>{{$unidad->descripcion}} </option>
                                            @else
                                                <option value={{$unidad->idunidad}}>{{$unidad->descripcion}} </option>
                                            @endif
                                        @endforeach
                                    </select>
                                    <div class="invalid-feedback">
                                        Por favor seleccione la Unidad.
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-7">
                                <div class="form-group ">
                                    <label for="txtPresentacion">Presentación</label>
                                    <input type="text" class="form-control " id="txtPresentacion" name="txtPresentacion"
                                           value="{{$producto->presentacion}}" placeholder="Ingrese la Presentación" required autofocus maxlength="50">
                                    <div class="invalid-feedback">
                                        Por favor ingrese una Presentación con 50 caracteres como máximo.
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group ">
                            <label for="txtTipo">Tipo</label>
                            <select class="form-control btn-light " id="txtTipo" name="txtTipo" >
                                @foreach($tipos as $tipo)
                                    @if($tipo->idtipo==$producto->idtipo)
                                        <option value={{$tipo->idtipo}} selected>{{$tipo->descripcion}} </option>
                                    @else
                                        <option value={{$tipo->idtipo}}>{{$tipo->descripcion}} </option>
                                    @endif
                                @endforeach
                            </select>
                            <div class="invalid-feedback">
                                Por favor seleccione un tipo.
                            </div>
                        </div>

                        <!-- SI EL ROL TIENE PERMISOS PARA EDITAR -->
                        <button type="submit" class="btn btn-warning">Actualizar <i class="fas fa-save iconoBoton"></i></button>

                        <button type="button" class="btn btn-secondary float-right" onclick="window.location='{{ route("productos.lista") }}'">Cancelar <i class="fas fa-undo-alt iconoBoton"></i></button>
                    </fieldset>
                </form>
            </div>

            <div class="col-md-2">
            </div>
        </div>
    </div>


@endsection

resources/views/producto/eliminar-producto.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 subtitulo">
                Mantenimiento de Productos
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-2">
            </div>

            <div class="col-md-6 col-sm-12">
                <form class="needs-validation"  action="{{action('ProductoController@destroy',$producto->idproducto)}}" method="post" enctype="multipart/form-data" novalidate>
                    @csrf
                    @method('DELETE')
                    <fieldset>
                        <legend class="sumario">Eliminar Producto</legend>
                        @if(count($errors)>0)
                        <!-- SI HUBIERA ERRORES SE MUESTRA UNA LISTA CON LOS ERRORES ENCONTRADOS   -->
                            <div class="alert alert-danger">
                                <ul><!--SE REALIZA UN BUCLE PARA MOSTRAR LOS ERRORES -->
                                    @foreach($errors->all() as $error)
                                        <li>{{$error}}</li><!-- SE MUESTRA EL ERROR  -->
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <div class="form-group">
                            <label for="txtCodigo">Código</label>
                            <input type="text" class="form-control" id="txtCodigo" name="txtCodigo"
                                   value="{{$producto->idproducto}}" placeholder="Ingrese un Codigo" readonly >
                            <div class="invalid-feedback">
                                Por favor ingrese un Codigo
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="txtDescripcion">Descripcion</label>
                            <input type="text" class="form-control" id="txtDescripcion" name="txtDescripcion"
                                   value="{{$producto->descripcion}}" readonly   >
                            <div class="invalid-feedback">
                                Por favor ingrese una descripcion.
                            </div>
                        </div>

                        <div class="row justify-content-center align-items-center">
                            <div class="col-md-5">
                                <div class="form-group ">
                                    <label for="txtPresentacion">Unidad</label>
                                    <input type="text" class="form-control" id="txtUnidad" name="txtUnidad"
                                           value="{{$producto->unidadMedida->descripcion}}" readonly   >
                                    <div class="invalid-feedback">
                                        Por favor seleccione una unidad.
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-7">
                                <div class="form-group ">
                                    <label for="txtPresentacion">Presentación</label>
                                    <input type="text" class="form-control" id="txtPresentacion" name="txtPresentacion"
                                           value="{{$producto->presentacion}}" readonly   >
                                    <div class="invalid-feedback">
                                        Por favor ingrese la presentación.
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group ">
                            <label for="txtTipo">Tipo</label>
                            <input type="text" class="form-control" id="txtTipo" name="txtTipo"
                                   value="{{$producto->tipo->descripcion}}" readonly   >

                            <div class="invalid-feedback">
                                Por favor seleccione un tipo.
                            </div>
                        </div>

                        <!-- SI EL ROL TIENE PERMISOS PARA EDITAR -->
                        <button type="submit" class="btn btn-danger">Eliminar <i class="fas fa-trash-alt iconoBoton"></i></button>

                        <button type="button" class="btn btn-secondary float-right" onclick="window.location='{{ route("productos.lista") }}'">Cancelar <i class="fas fa-undo-alt iconoBoton"></i></button>
                    </fieldset>
                </form>
            </div>

            <div class="col-md-2">
            </div>
        </div>
    </div>


@endsection

resources/views/producto/lista-producto.blade.php
@extends('layouts.app')

@section('content')

    <div class="container-fluid">
        <div class="row justify-content-center align-items-center">
            <div class="col-3"></div>
            <div class="col-6 subtitulo Titulos">
                MANTENIMIENTO DE PRODUCTOS
            </div>
            <div class="col-3">
                <!-- SI EL ROL TIENE PERMISOS PARA EDITAR -->
                <a class="btn btn-success" href="{{route('producto.create')}}">
                    Crear <i class="fas fa-file-alt"></i>
                </a>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <table class="table">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">CODIGO</th>
                        <th scope="col">DESCRIPCION</th>
                        <th scope="col">PRESENTACION</th>
                        <th scope="col">UNIDAD</th>
                        <th scope="col">TIPO</th>
                        <th scope="col">ACCIONES</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($productos as $producto)
                        <tr>
                            <td>{{$producto->idproducto}}</td>
                            <td>{{$producto->descripcion}}</td>
                            <td>{{$producto->presentacion}}</td>
                            <td>{{$producto->unidadMedida->descripcion}}</td>
                            <td>{{$producto->tipo->descripcion}}</td>

                            <td>
                                <a class="btn btn-warning" href="{{action('ProductoController@edit',$producto->idproducto)}}">
                                    Editar <i class="fas fa-pencil-alt"></i>
                                </a>

                                <a class="btn btn-danger" href="{{action('ProductoController@show',$producto->idproducto)}}">
                                    Eliminar <i class="fas fa-trash-alt"></i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="row">
                    <div class="mx-auto">
                        {{$productos->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection