routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','IndexController@index')->name('index');

Route::get('/demo','UsuarioController@lista');

Route::resource('almacen','AlmacenController');
Route::get('/almacenes/lista','AlmacenController@index')->name('almacenes.lista');

Route::resource('producto','ProductoController');
Route::get('/productos/lista','ProductoController@index')->name('productos.lista');

Route::resource('usuario','UsuarioController');
Route::get('/usuarios/lista','UsuarioController@index')->name('usuarios.lista');

Route::resource('registroEntrada','RegistroEntradaController');
Route::get('/registroentradas/lista','RegistroEntradaController@index')->name('registroentradas.lista');

Route::resource('registroSalida','RegistroSalidaController');
Route::get('/registrosalidas/lista','RegistroSalidaController@index')->name('registrosalidas.lista');

Route::get('/kardex/lista','KardexController@index')->name('kardex.lista');

Route::resource('existencia','ExistenciaController');
Route::get('/inventario/lista','InventarioController@index')->name('inventario.lista');
Route::get('/inventario/{almacen}','InventarioController@detalle');
Route::get('/inventario/exportar/{almacen}','InventarioController@exportar');

Route::get('/kardex/exportar/{lista}','KardexController@exportar');

Route::resource('documento','DocumentoController');
Route::resource('disposicion','DisposicionController');

Route::get('/login','LoginController@index')->name('login');
Route::post('/loginprocess','LoginController@validar')->name('logueo');
Route::get('/logout','LoginController@logout')->name('logout');
Route::get('/loginprocess','LoginController@index');

Route::resource('ticket','TicketController');
Route::get('/tickets/lista','TicketController@index')->name('tickets.lista');
Route::get('/ticketNotificado/{idnotificacion}','TicketController@showTicketNotificado');
Route::put('/ticketNotificado/{idnotificacion}','TicketController@updateTicketNotificado');

Route::get('/acercade/mostrar','HomeController@mostrar')->name('acercade.mostrar');
#Auth::routes();

app/Ticket.php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model;

class Ticket extends Model
{

    protected $primaryKey = 'idticket';

    public function prioridad(){
        return $this->belongsTo('App\Prioridad','idprioridad','idprioridad');
    }

    public function usuarioOrigen(){
        return $this->belongsTo('App\Usuario','idusuarioOrigen','idusuario');
    }

    public function usuarioDestino(){
        return $this->belongsTo('App\Usuario','idusuarioDestino','idusuario');
    }
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use App\Notifications\TicketNotificacion;
use App\Secuencia;
use App\Ticket;
use App\Prioridad;
use App\User;
use App\Usuario;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class TicketController extends Controller
{

    public function __construct()
    {
        #VALIDAR QUE EL USUARIO ESTE AUTENTICADO
        $this->middleware('auth');
    }

    public function index()
    {

        $tickets=Ticket::where('idusuarioOrigen','=',Auth::user()->idusuario)->paginate(10);
        return view('ticket.lista-ticket',compact('tickets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $prioridades=Prioridad::all();
        $usuarios=Usuario::where('idusuario','<>',(int)Auth::user()->idusuario)->get();
        return view('ticket.crear-ticket',compact('prioridades'),compact('usuarios'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $fecha=$request->get('txtFecha');
        $titulo=$request->get('txtTitulo');
        $idprioridad=$request->get('txtPrioridad');
        $contenido=$request->get('txtContenido');
        $idusuario=$request->get('txtUsuario');

        $ticket=new Ticket();
        $ticket->fecha=$fecha;
        $ticket->idticket=Secuencia::nextid();
        $ticket->titulo=$titulo;
        $ticket->contenido=$contenido;
        $ticket->idprioridad=(int)$idprioridad;
        $ticket->idusuarioOrigen=Auth::user()->idusuario;
        $ticket->idusuarioDestino=(int)$idusuario;
        $ticket->atendido=false;

        $ticket->save();

        #$user=User::find((int)$idusuario);
        #$user->notify(new TicketNotificacion($ticket));

        return redirect()->route('tickets.lista');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $ticket=Ticket::find((int)$id);

        return view('ticket.eliminar-ticket',compact('ticket'));
    }

    public function showTicketNotificado($idticket)
    {
        $ticket=Ticket::find((int)$idticket);

        return view('ticket.resolver-ticket',['ticket'=>$ticket]);
    }

    public function edit($id)
    {

        $prioridades=Prioridad::all();
        $usuarios=Usuario::where('idusuario','<>',(int)Auth::user()->idusuario)->get();

        $ticket=Ticket::find((int)$id);


        return view('ticket.editar-ticket',['ticket'=>$ticket,'prioridades'=>$prioridades,'usuarios'=>$usuarios ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $fecha=$request->get('txtFecha');
        $titulo=$request->get('txtTitulo');
        $idprioridad=$request->get('txtPrioridad');
        $contenido=$request->get('txtContenido');
        $idusuario=$request->get('txtUsuario');

        $ticketBuscado = Ticket::find((int)$id);
        $ticketBuscado->titulo=$titulo;
        $ticketBuscado->contenido=$contenido;
        $ticketBuscado->idprioridad=(int)$idprioridad;
        $ticketBuscado->idusuarioDestino=(int)$idusuario;
        $ticketBuscado->update();
        return redirect()->route('tickets.lista');
    }


    public function updateTicketNotificado(Request $request, $id)
    {
        $ticketBuscado = Ticket::find((int)$id);
        $ticketBuscado->atendido=true;
        $ticketBuscado->update();

        return redirect()->route('index');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {


        $ticketBuscado=Ticket::find((int)$id);
        $ticketBuscado->delete();

        return redirect()->route('tickets.lista');
    }
}

resources/views/ticket/crear-ticket.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 subtitulo">
                CREAR TICKET
            </div>
        </div>
    </div>


    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-2">
            </div>

            <div class="col-md-6 col-sm-12">
                <form class="needs-validation"  action="{{action('TicketController@store')}}" method="post" enctype="multipart/form-data" novalidate>
                    @csrf
                    <fieldset>
                        <legend class="sumario">Nuevo Ticket</legend>

                        <div class="form-group margenes-input">
                            <label for="txtFecha">Fecha</label>
                            <input type="date" class="form-control" id="txtFecha" name="txtFecha" readonly
                                   value="<?=date('Y-m-d', time());?>"  >
                        </div>

                        <div class="form-group margenes-input">
                            <label for="txtTitulo">Titulo</label>
                            <input type="text" class="form-control" id="txtTitulo" name="txtTitulo"  placeholder="Ingrese un Titulo" required autofocus maxlength="50">
                            <div class="invalid-feedback">
                                Por favor ingrese un Titulo.
                            </div>
                        </div>

                        <div class="row justify-content-center align-items-center">
                            <div class="col-md-6">
                                <label for="txtPrioridad">Prioridad</label>
                                <select class="form-control btn-light" id="txtPrioridad" name="txtPrioridad" >
                                    @foreach($prioridades as $prioridad)
                                        <option value={{$prioridad->idprioridad}}>{{$prioridad->descripcion}} </option>
                                    @endforeach

                                </select>
                                <div class="invalid-feedback">
                                    Por favor seleccione una prioridad.
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label for="txtUsuario">Usuario</label>
                                <select class="form-control btn-light" id="txtUsuario" name="txtUsuario" >
                                    @foreach($usuarios as $usuario)
                                        <option value={{$usuario->idusuario}}>{{$usuario->nombres}} </option>
                                    @endforeach
                                </select>
                                <div class="invalid-feedback">
                                    Por favor seleccione un usuario.
                                </div>
                            </div>
                        </div>



                        <div class="form-group margenes-input">
                            <label for="txtContenido">Contenido</label>
                            <textarea  class="form-control" id="txtContenido" name="txtContenido"  rows="1"  placeholder="Ingrese un Contenido" required autofocus >

                            </textarea>
                            <div class="invalid-feedback">
                                Por favor ingrese un Contenido.
                            </div>
                        </div>

                        <!-- SI EL ROL TIENE PERMISOS PARA EDITAR -->
                        <button type="submit" class="btn btn-success">Registrar <i class="fas fa-save iconoBoton"></i></button>

                        <button type="button" class="btn btn-secondary float-right" onclick="window.location='{{ route("tickets.lista") }}'">Cancelar <i class="fas fa-undo-alt iconoBoton"></i></button>
                    </fieldset>
                </form>
            </div>

            <div class="col-md-2">
            </div>
        </div>
    </div>


@endsection

resources/views/ticket/editar-ticket.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 subtitulo">
                Mantenimiento de Ticket
            </div>
        </div>
    </div>


    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-2">
            </div>

            <div class="col-md-6 col-sm-12">
                <form class="needs-validation"  action="{{action('TicketController@update',$ticket->idticket)}}" method="post" enctype="multipart/form-data" novalidate>
                    @csrf
                    {{ method_field('PUT') }}
                    <fieldset>
                        <legend class="sumario">Editar Ticket</legend>
                    @if(count($errors)>0)
                        <!-- SI HUBIERA ERRORES SE MUESTRA UNA LISTA CON LOS ERRORES ENCONTRADOS   -->
                            <div class="alert alert-danger">
                                <ul><!--SE REALIZA UN BUCLE PARA MOSTRAR LOS ERRORES -->
                                    @foreach($errors->all() as $error)
                                        <li>{{$error}}</li><!-- SE MUESTRA EL ERROR  -->
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <div class="form-group margenes-input">
                            <label for="txtFecha">Fecha</label>
                            <input type="text" class="form-control" id="txtFecha" name="txtFecha" readonly
                                   value= "{{$ticket->fecha}}" >
                        </div>

                        <div class="form-group margenes-input">
                            <label for="txtTitulo">Titulo</label>
                            <input type="text" class="form-control" id="txtTitulo" name="txtTitulo"  placeholder="Ingrese un Titulo"
                                   value="{{$ticket->titulo}}" required autofocus maxlength="50">
                            <div class="invalid-feedback">
                                Por favor ingrese un Titulo.
                            </div>
                        </div>

                        <div class="row justify-content-center align-items-center">
                            <div class="col-md-6">
                                <label for="txtPrioridad">Prioridad</label>
                                <select class="form-control btn-light" id="txtPrioridad" name="txtPrioridad" >
                                    @foreach($prioridades as $prioridad)
                                        @if($prioridad->idprioridad==$ticket->idprioridad)
                                            <option value={{$prioridad->idprioridad}} selected>{{$prioridad->descripcion}} </option>
                                        @else
                                            <option value={{$prioridad->idprioridad}}>{{$prioridad->descripcion}} </option>
                                        @endif
                                    @endforeach

                                </select>
                                <div class="invalid-feedback">
                                    Por favor seleccione una prioridad.
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label for="txtUsuario">Usuario</label>
                                <select class="form-control btn-light" id="txtUsuario" name="txtUsuario" >
                                    @foreach($usuarios as $usuario)
                                        @if($usuario->idusuario==$ticket->idusuarioOrigen)
                                            <option value={{$usuario->idusuario}} selected>{{$usuario->nombres}} </option>
                                        @else
                                            <option value={{$usuario->idusuario}}>{{$usuario->nombres}} </option>
                                        @endif
                                    @endforeach
                                </select>
                                <div class="invalid-feedback">
                                    Por favor seleccione un usuario.
                                </div>
                            </div>
                        </div>



                        <div class="form-group margenes-input">
                            <label for="txtContenido">Contenido</label>
                            <textarea  class="form-control" id="txtContenido" name="txtContenido"  rows="1"  placeholder="Ingrese un Contenido" required autofocus >
                                {{$ticket->contenido}}
                            </textarea>
                            <div class="invalid-feedback">
                                Por favor ingrese un Contenido.
                            </div>
                        </div>

                        <!-- SI EL ROL TIENE PERMISOS PARA EDITAR -->
                        <button type="submit" class="btn btn-warning">Actualizar<i class="fas fa-save iconoBoton"></i></button>

                        <button type="button" class="btn btn-secondary float-right" onclick="window.location='{{ route("tickets.lista") }}'">Cancelar <i class="fas fa-undo-alt iconoBoton"></i></button>
                    </fieldset>
                </form>
            </div>

            <div class="col-md-2">
            </div>
        </div>
    </div>


@endsection

resources/views/ticket/eliminar-ticket.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 subtitulo">
                Mantenimiento de Ticket
            </div>
        </div>
    </div>


    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-2">
            </div>

            <div class="col-md-6 col-sm-12">
                <form class="needs-validation"  action="{{action('TicketController@destroy',$ticket->idticket)}}" method="post" enctype="multipart/form-data" novalidate>
                    @csrf
                    {{ method_field('DELETE') }}
                    <fieldset>
                        <legend class="sumario">Eliminar Ticket</legend>
                    @if(count($errors)>0)
                        <!-- SI HUBIERA ERRORES SE MUESTRA UNA LISTA CON LOS ERRORES ENCONTRADOS   -->
                            <div class="alert alert-danger">
                                <ul><!--SE REALIZA UN BUCLE PARA MOSTRAR LOS ERRORES -->
                                    @foreach($errors->all() as $error)
                                        <li>{{$error}}</li><!-- SE MUESTRA EL ERROR  -->
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <div class="form-group margenes-input">
                            <label for="txtFecha">Fecha</label>
                            <input type="text" class="form-control" id="txtFecha" name="txtFecha" readonly
                                   value= "{{$ticket->fecha}}" >
                        </div>

                        <div class="form-group margenes-input">
                            <label for="txtTitulo">Titulo</label>
                            <input type="text" class="form-control" id="txtTitulo" name="txtTitulo"  placeholder="Ingrese un Titulo"
                                   value="{{$ticket->titulo}}" readonly>
                            <div class="invalid-feedback">
                                Por favor ingrese un Titulo.
                            </div>
                        </div>

                        <div class="row justify-content-center align-items-center">
                            <div class="col-md-6">
                                <div class="form-group margenes-input">
                                    <label for="txtTitulo">Prioridad</label>
                                    <input type="text" class="form-control" id="txtTitulo" name="txtTitulo"  placeholder="Ingrese un Titulo"
                                           value="{{$ticket->prioridad->descripcion}}" readonly>
                                    <div class="invalid-feedback">
                                        Por favor ingrese una Prioridad
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group margenes-input">
                                    <label for="txtUsuario">Usuario</label>
                                    <input type="text" class="form-control" id="txtUsuario" name="txtUsuario"  placeholder="Ingrese un Usuario"
                                           value="{{$ticket->usuarioDestino->nombres}}" readonly>

                                    <div class="invalid-feedback">
                                        Por favor ingrese una Prioridad
                                    </div>
                                </div>
                            </div>
                        </div>



                        <div class="form-group margenes-input">
                            <label for="txtContenido">Contenido</label>
                            <textarea  class="form-control" id="txtContenido" name="txtContenido"  rows="2" cols="50" readonly >
                                {{$ticket->contenido}}
                            </textarea>
                            <div class="invalid-feedback">
                                Por favor ingrese un Contenido.
                            </div>
                        </div>

                        <!-- SI EL ROL TIENE PERMISOS PARA EDITAR -->
                        <button type="submit" class="btn btn-danger">Eliminar<i class="fas fa-save iconoBoton"></i></button>

                        <button type="button" class="btn btn-secondary float-right" onclick="window.location='{{ route("tickets.lista") }}'">Cancelar <i class="fas fa-undo-alt iconoBoton"></i></button>
                    </fieldset>
                </form>
            </div>

            <div class="col-md-2">
            </div>
        </div>
    </div>


@endsection

resources/views/ticket/lista-ticket.blade.php
@extends('layouts.app')

@section('content')

    <div class="container-fluid">
        <div class="row justify-content-center align-items-center">
            <div class="col-3"></div>
            <div class="col-6 subtitulo Titulos">
                Listado de Tickets
            </div>

            <div class="col-3">
                <!-- SI EL ROL TIENE PERMISOS PARA EDITAR -->
                <a class="btn btn-success" href="{{route('ticket.create')}}">
                    Crear <i class="fas fa-file-alt"></i>
                </a>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <table class="table">
                    <thead class="thead thead-light">
                    <tr>
                        <th scope="col">FECHA</th>
                        <th scope="col">TITULO</th>
                        <th scope="col">PRIORIDAD</th>
                        <th scope="col">ATENDIDO</th>
                        <th scope="col">ACCIONES</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($tickets as $ticket)
                        <tr>
                            <td>{{$ticket->fecha}}</td>
                            <td>{{$ticket->titulo}}</td>
                            <td>{{$ticket->prioridad->descripcion}}</td>
                            <td>
                                <div class="form-check">
                                    <input class="form-check-input position-static" type="checkbox" {{$ticket->atendido ? 'checked' : '' }} disabled >
                                </div>
                            </td>

                            <td>
                                <!-- SI EL TICKET ESTA ATENDIDO NO SE MUESTRA -->
                                @if($ticket->atendido==false)
                                    <a class="btn btn-warning" href="{{action('TicketController@edit',$ticket->idticket)}}">
                                        Editar <i class="fas fa-pencil-alt iconoBoton"></i>
                                    </a>

                                    <a class="btn btn-danger" href="{{action('TicketController@show',$ticket->idticket)}}">
                                        Eliminar <i class="fas fa-trash-alt IconColorRojo"></i>
                                    </a>
                                @endif


                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="row">
                    <div class="mx-auto">
                        {{$tickets->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/ticket/resolver-ticket.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 subtitulo">
                Mantenimiento de Ticket
            </div>
        </div>
    </div>


    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-2">
            </div>

            <div class="col-md-6 col-sm-12">
                <form class="needs-validation"  action="{{action('TicketController@updateTicketNotificado',$ticket->idticket)}}" method="post" enctype="multipart/form-data" novalidate>
                    @csrf
                    {{ method_field('PUT') }}
                    <fieldset>
                        <legend class="sumario">Resolver Ticket</legend>
                    @if(count($errors)>0)
                        <!-- SI HUBIERA ERRORES SE MUESTRA UNA LISTA CON LOS ERRORES ENCONTRADOS   -->
                            <div class="alert alert-danger">
                                <ul><!--SE REALIZA UN BUCLE PARA MOSTRAR LOS ERRORES -->
                                    @foreach($errors->all() as $error)
                                        <li>{{$error}}</li><!-- SE MUESTRA EL ERROR  -->
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <div class="form-group margenes-input">

                            <label for="txtFecha">Fecha</label>
                            <input type="text" class="form-control" id="txtFecha" name="txtFecha" readonly
                                   value= "{{$ticket->fecha}}" >
                        </div>

                        <div class="form-group margenes-input">
                            <label for="txtTitulo">Titulo</label>
                            <input type="text" class="form-control" id="txtTitulo" name="txtTitulo"  placeholder="Ingrese un Titulo"
                                   value="{{$ticket->titulo}}" readonly>
                            <div class="invalid-feedback">
                                Por favor ingrese un Titulo.
                            </div>
                        </div>

                        <div class="row justify-content-center align-items-center">
                            <div class="col-md-6">
                                <div class="form-group margenes-input">
                                    <label for="txtTitulo">Prioridad</label>
                                    <input type="text" class="form-control" id="txtTitulo" name="txtTitulo"  placeholder="Ingrese un Titulo"
                                           value="{{$ticket->prioridad->descripcion}}" readonly>
                                    <div class="invalid-feedback">
                                        Por favor ingrese una Prioridad
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group margenes-input">
                                    <label for="txtUsuario">Usuario</label>
                                    <input type="text" class="form-control" id="txtUsuario" name="txtUsuario"  placeholder="Ingrese un Usuario"
                                           value="{{$ticket->usuarioDestino->nombres}}" readonly>

                                    <div class="invalid-feedback">
                                        Por favor ingrese una Prioridad
                                    </div>
                                </div>
                            </div>
                        </div>



                        <div class="form-group margenes-input">
                            <label for="txtContenido">Contenido</label>
                            <textarea  class="form-control" id="txtContenido" name="txtContenido"  rows="2" cols="50" readonly >
                                {{$ticket->contenido}}
                            </textarea>
                            <div class="invalid-feedback">
                                Por favor ingrese un Contenido.
                            </div>
                        </div>

                        <!-- SI EL ROL TIENE PERMISOS PARA EDITAR -->
                        <button type="submit" class="btn btn-warning">Resolver<i class="fas fa-save icono"></i></button>

                        <button type="button" class="btn btn-secondary float-right" onclick="window.location='{{ route("tickets.lista") }}'">Cancelar <i class="fas fa-undo-alt iconoBoton"></i></button>
                    </fieldset>
                </form>
            </div>

            <div class="col-md-2">
            </div>
        </div>
    </div>


@endsection