routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','IndexController@index')->name('index');

Route::get('/demo','UsuarioController@lista');

Route::resource('almacen','AlmacenController');
Route::get('/almacenes/lista','AlmacenController@index')->name('almacenes.lista');

Route::resource('producto','ProductoController');
Route::get('/productos/lista','ProductoController@index')->name('productos.lista');

Route::resource('usuario','UsuarioController');
Route::get('/usuarios/lista','UsuarioController@index')->name('usuarios.lista');

Route::resource('registroEntrada','RegistroEntradaController');
Route::get('/registroentradas/lista','RegistroEntradaController@index')->name('registroentradas.lista');

Route::resource('registroSalida','RegistroSalidaController');
Route::get('/registrosalidas/lista','RegistroSalidaController@index')->name('registrosalidas.lista');

Route::get('/kardex/lista','KardexController@index')->name('kardex.lista');

Route::resource('existencia','ExistenciaController');
Route::get('/inventario/lista','InventarioController@index')->name('inventario.lista');
Route::get('/inventario/{almacen}','InventarioController@detalle');
Route::get('/inventario/exportar/{almacen}','InventarioController@exportar');

Route::get('/kardex/exportar/{lista}','KardexController@exportar');

Route::resource('documento','DocumentoController');
Route::resource('disposicion','DisposicionController');

Route::get('/login','LoginController@index')->name('login');
Route::post('/loginprocess','LoginController@validar')->name('logueo');
Route::get('/logout','LoginController@logout')->name('logout');
Route::get('/loginprocess','LoginController@index');

Route::resource('ticket','TicketController');
Route::get('/tickets/lista','TicketController@index')->name('tickets.lista');
Route::get('/ticketNotificado/{idnotificacion}','TicketController@showTicketNotificado');
Route::put('/ticketNotificado/{idnotificacion}','TicketController@updateTicketNotificado');

Route::get('/acercade/mostrar','HomeController@mostrar')->name('acercade.mostrar');
#Auth::routes();

app/RegistroEntrada.php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model;

class RegistroEntrada extends Model
{
    protected $primaryKey = 'identrada';

    public function almacen(){
        return $this->belongsTo('App\Almacen','idalmacen','idalmacen');
    }

    public function documento(){
        return $this->belongsTo('App\Documento','iddocumento','iddocumento');
    }

    public function usuario(){
        return $this->belongsTo('App\Usuario','idusuario','idusuario');
    }

    #UN REGISTRO DE ENTRADA TIENE MUCHOS PRODUCTOS
    public function detalleRegistroEntradas()
    {
        return $this->embedsMany('App\DetalleRegistroEntrada');
    }

}

app/Http/Controllers/RegistroEntradaController.php
<?php

namespace App\Http\Controllers;

use App\DetalleRegistroSalida;
use App\Disposicion;
use App\Documento;
use App\Existencia;
use App\Periodo;
use App\Producto;
use App\Secuencia;
use App\Tipo;
use App\Usuario;
use App\Almacen;
use App\DetalleRegistroEntrada;
use App\RegistroEntrada;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class RegistroEntradaController extends Controller
{
    public function __construct()
    {
        #VALIDAR QUE EL USUARIO ESTE AUTENTICADO
        $this->middleware('auth');
    }

    public function index()
    {
        #SE VALIDA EL ROL AUTORIZADO
        Auth::user()->authorizeRoles(['ALMACEN']);

        $registroentradas=RegistroEntrada::all();

        return view('registroEntrada.lista-registroentrada',compact('registroentradas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        #SE VALIDA EL ROL AUTORIZADO
        Auth::user()->authorizeRoles(['ALMACEN']);

        $almacenes=Almacen::all();
        $usuarios=Usuario::all();
        $tipos=Tipo::all();
        $productos = Producto::all();
        $documentos=Documento::all();
        $disposiciones=Disposicion::all();
        $registroentradas=RegistroEntrada::all();
        $periodos=Periodo::all();

        return view('registroEntrada.crear-registroentrada',[
            'almacenes'=>$almacenes,
            'usuarios'=>$usuarios,
            'tipos'=>$tipos,
            'documentos'=>$documentos,
            'productos' => $productos,
            'disposiciones' => $disposiciones,
            'registroentradas' => $registroentradas,
            'periodos'=>$periodos
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       //NO SE USA ESTE MÉTODO , SE USA DIRECTAMENTE EL COMPONENTE
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\RegistroEntrada  $registroEntrada
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        #SE VALIDA EL ROL AUTORIZADO
        Auth::user()->authorizeRoles(['ALMACEN']);

        $registroentradas=RegistroEntrada::find((int)$id);
        return view('registroEntrada.eliminar-registroentrada', compact('registroentradas'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\RegistroEntrada  $registroEntrada
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        #SE VALIDA EL ROL AUTORIZADO
        Auth::user()->authorizeRoles(['ALMACEN']);

        $almacenes=Almacen::all();
        $usuarios=Usuario::all();
        $registroentradas=RegistroEntrada::find((int)$id);
        //dd($registroentradas->detalleRegistroEntradas);
        return view('registroEntrada.editar-registroentrada',['almacenes'=>$almacenes,'usuarios'=>$usuarios,
            'registroentradas'=>$registroentradas]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\RegistroEntrada  $registroEntrada
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, RegistroEntrada $registroEntrada)
    {
        //NO SE REALIZAN ACTUALIZACIONES
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\RegistroEntrada  $registroEntrada
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        #SE VALIDA EL ROL AUTORIZADO
        Auth::user()->authorizeRoles(['ALMACEN']);

        $registroentradasBuscado=RegistroEntrada::find((int)$id);
        $listaDetalle=$registroentradasBuscado->detalleRegistroEntradas;

        #RECOREMOS NUESTRO DETALLE
        foreach ($listaDetalle as $detalle){
            #SE BUSCA LA EXISTENCIA Y SE DISMINUYE SU STOCK
            $existencia = Existencia::where('idalmacen','=',$registroentradasBuscado->idalmacen)->where('idproducto','=', $detalle->idproducto)->first();
            $existencia->stock=$existencia->stock-$detalle->cantidad;
            $existencia->update();
        }

        $registroentradasBuscado->delete();
        return redirect()->route('registroentradas.lista');
    }

}

resources/views/registroEntrada/crear-registroentrada.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 subtitulo">
                Ingreso
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12">
                @livewire('crear-ingreso')
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    <script>
    </script>
@endsection

resources/views/registroEntrada/editar-registroentrada.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 subtitulo">
                Ingreso
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-2">
            </div>

            <div class="col-md-12 col-sm-12">
                <form class="needs-validation"  action="" method="post" enctype="multipart/form-data" novalidate>
                    @csrf
                    {{ method_field('PUT') }}
                    <fieldset>

                        <legend class="sumario">Detalle Ingreso</legend>

                        <div class="form-group margenes-input col-sm-5 float-left">
                            <label for="txtTipo">Tipo</label>
                            <input type="text" class="form-control" id="txtTipo" name="txtTipo"
                                   value="{{$registroentradas->Almacen->Tipo->descripcion}}" readonly   >
                            <div class="invalid-feedback">
                                Por favor ingrese una descripcion.
                            </div>
                        </div>

                        <div class="form-group margenes-input col-md-5 float-lg-left">
                            <label for="txtAlmacen">Almacen</label>
                            <input type="text" class="form-control" id="txtAlmacen" name="txtAlmacen"
                                   value="{{$registroentradas->Almacen->descripcion}}" readonly   >
                            <div class="invalid-feedback">
                                Por favor ingrese una descripcion.
                            </div>
                        </div>

                        <div class="form-group margenes-input col-sm-2 float-left">
                            <label for="txtOperacion">Operación</label>
                            <input type="text" class="form-control" id="txtOperacion" name="txtOperacion"
                                   value="1234" readonly   >
                            <div class="invalid-feedback">
                                Por favor ingrese una descripcion.
                            </div>
                        </div>

                        <div class="form-group margenes-input col-sm-3 float-left">
                            <label for="txtFecha">F. Ingreso</label>
                            <input type="text" class="form-control" id="txtFecha" name="txtFecha"
                                   value="{{$registroentradas->fecha}}" readonly   >
                            <div class="invalid-feedback">
                                Por favor ingrese una descripcion.
                            </div>
                        </div>

                        <div class="form-group margenes-input col-sm-3 float-left">
                            <label for="txtDocumento">Documento</label>
                            <input type="text" class="form-control" id="txtDocumento" name="txtDocumento"
                                   value="{{$registroentradas->Documento->descripcion}}" readonly   >
                            <div class="invalid-feedback">
                                Por favor ingrese una descripcion.
                            </div>
                        </div>

                        <div class="form-group margenes-input col-sm-2 float-left">
                            <label for="txtSerie">Serie</label>
                            <input type="text" class="form-control" id="txtSerie" name="txtSerie"
                                   value="{{$registroentradas->serie}}" readonly   >
                            <div class="invalid-feedback">
                                Por favor ingrese una descripcion.
                            </div>
                        </div>

                        <div class="form-group margenes-input col-sm-2 float-left">
                            <label for="txtNumero">Número</label>
                            <input type="text" class="form-control" id="txtNumero" name="txtNumero"
                                   value="{{$registroentradas->numero}}" readonly   >
                            <div class="invalid-feedback">
                                Por favor ingrese una descripcion.
                            </div>
                        </div>

                        <table class="table">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col">CÓDIGO</th>
                                <th scope="col">DESCRIPCIÓN</th>
                                <th scope="col">DISPOSICIÓN</th>
                                <th scope="col">CANTIDAD</th>
                                <th scope="col">LOTE</th>
                                <th scope="col">VENCIMIENTO</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($registroentradas->detalleRegistroEntradas as $detalles)
                                <tr>
                                    <td>{{$detalles->Producto->idproducto}}</td>
                                    <td>{{$detalles->Producto->descripcion}}</td>
                                    <td>{{$detalles->Disposicion->descripcion}}</td>
                                    <td>{{$detalles->cantidad}}</td>
                                    <td>{{$detalles->lote}}</td>
                                    <td>{{$detalles->vencimiento}}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                        <button type="button" class="btn btn-secondary float-right" onclick="window.location='{{ redirect()->back()->getTargetUrl() }}'">Retornar <i class="fas fa-undo-alt iconoBoton"></i></button>

                    </fieldset>
                </form>
            </div>

            <div class="col-md-2">
            </div>
        </div>
    </div>


@endsection

resources/views/registroEntrada/eliminar-registroentrada.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 subtitulo">
                Ingreso
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-2">
            </div>

            <div class="col-md-12 col-sm-12">
                <form class="needs-validation"  action="{{action('RegistroEntradaController@destroy',$registroentradas->identrada)}}" method="post" enctype="multipart/form-data" novalidate>
                    @csrf
                    @method('DELETE')
                    <fieldset>

                        <legend class="sumario">Eliminar Ingreso</legend>

                        <div class="form-group margenes-input col-sm-5 float-left">
                            <label for="txtTipo">Tipo</label>
                            <input type="text" class="form-control" id="txtTipo" name="txtTipo"
                                   value="{{$registroentradas->almacen->tipo->descripcion}}" readonly   >
                            <div class="invalid-feedback">
                                Por favor ingrese una descripcion.
                            </div>
                        </div>

                        <div class="form-group margenes-input col-md-5 float-lg-left">
                            <label for="txtAlmacen">Almacen</label>
                            <input type="text" class="form-control" id="txtAlmacen" name="txtAlmacen"
                                   value="{{$registroentradas->Almacen->descripcion}}" readonly   >
                            <div class="invalid-feedback">
                                Por favor ingrese una descripcion.
                            </div>
                        </div>

                        <div class="form-group margenes-input col-sm-2 float-left">
                            <label for="txtOperacion">Operación</label>
                            <input type="text" class="form-control" id="txtOperacion" name="txtOperacion"
                                   value="1234" readonly   >
                            <div class="invalid-feedback">
                                Por favor ingrese una descripcion.
                            </div>
                        </div>

                        <div class="form-group margenes-input col-sm-3 float-left">
                            <label for="txtFecha">F. Ingreso</label>
                            <input type="text" class="form-control" id="txtFecha" name="txtFecha"
                                   value="{{$registroentradas->fecha}}" readonly   >
                            <div class="invalid-feedback">
                                Por favor ingrese una descripcion.
                            </div>
                        </div>

                        <div class="form-group margenes-input col-sm-3 float-left">
                            <label for="txtDocumento">Documento</label>
                            <input type="text" class="form-control" id="txtDocumento" name="txtDocumento"
                                   value="{{$registroentradas->Documento->descripcion}}" readonly   >
                            <div class="invalid-feedback">
                                Por favor ingrese una descripcion.
                            </div>
                        </div>

                        <div class="form-group margenes-input col-sm-2 float-left">
                            <label for="txtSerie">Serie</label>
                            <input type="text" class="form-control" id="txtSerie" name="txtSerie"
                                   value="{{$registroentradas->serie}}" readonly   >
                            <div class="invalid-feedback">
                                Por favor ingrese una descripcion.
                            </div>
                        </div>

                        <div class="form-group margenes-input col-sm-2 float-left">
                            <label for="txtNumero">Número</label>
                            <input type="text" class="form-control" id="txtNumero" name="txtNumero"
                                   value="{{$registroentradas->numero}}" readonly   >
                            <div class="invalid-feedback">
                                Por favor ingrese una descripcion.
                            </div>
                        </div>

                        <table class="table">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col">CÓDIGO</th>
                                <th scope="col">DESCRIPCIÓN</th>
                                <th scope="col">DISPOSICIÓN</th>
                                <th scope="col">CANTIDAD</th>
                                <th scope="col">LOTE</th>
                                <th scope="col">VENCIMIENTO</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($registroentradas->detalleRegistroEntradas as $detalles)
                                <tr>
                                    <td>{{$detalles->Producto->idproducto}}</td>
                                    <td>{{$detalles->Producto->descripcion}}</td>
                                    <td>{{$detalles->Disposicion->descripcion}}</td>
                                    <td>{{$detalles->cantidad}}</td>
                                    <td>{{$detalles->lote}}</td>
                                    <td>{{$detalles->vencimiento}}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <button type="submit" class="btn btn-danger">Eliminar <i class="fas fa-trash-alt iconoBoton"></i></button>

                        <button type="button" class="btn btn-secondary float-right" onclick="window.location='{{ route("registroentradas.lista") }}'">Cancelar <i class="fas fa-undo-alt iconoBoton"></i></button>

                    </fieldset>
                </form>
            </div>

            <div class="col-md-2">
            </div>
        </div>
    </div>


@endsection

resources/views/registroEntrada/lista-registroentrada.blade.php
@extends('layouts.app')

@section('content')

    <div class="container-fluid">
        <div class="row justify-content-center align-items-center">
            <div class="col-3"></div>
            <div class="col-6 subtitulo Titulos">
                Listado de Ingresos
            </div>
            <div class="col-3">
                <!-- SI EL ROL TIENE PERMISOS PARA EDITAR -->
                <a class="btn btn-success" href="{{route('registroEntrada.create')}}">
                    Crear <i class="fas fa-file-alt"></i>
                </a>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <table class="table">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">F. INGRESO</th>
                        <th scope="col">TIPOS</th>
                        <th scope="col">ALMACEN</th>
                        <th scope="col">SERIE</th>
                        <th scope="col">NÚMERO</th>
                        <th scope="col">USUARIO</th>
                        <th scope="col">ACCIONES</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($registroentradas as $registroentrada)
                        <tr>
                            <td>{{$registroentrada->fecha}}</td>
                            <td>{{$registroentrada->Almacen->Tipo->descripcion}}</td>
                            <td>{{$registroentrada->Almacen->descripcion}}</td>
                            <td>{{$registroentrada->serie}}</td>
                            <td>{{$registroentrada->numero}}</td>
                            <td>{{$registroentrada->Usuario->nombres}}</td>

                            <td>

                                <a class="btn btn-warning" href="{{action('RegistroEntradaController@edit',$registroentrada->identrada)}}">
                                    Ver <i class="fas fa-pencil-alt"></i>
                                </a>

                                <a class="btn btn-danger" href="{{action('RegistroEntradaController@show',$registroentrada->identrada)}}">
                                    Eliminar <i class="fas fa-trash-alt"></i>
                                </a>

                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection