routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','IndexController@index')->name('index');

Route::get('/demo','UsuarioController@lista');

Route::resource('almacen','AlmacenController');
Route::get('/almacenes/lista','AlmacenController@index')->name('almacenes.lista');

Route::resource('producto','ProductoController');
Route::get('/productos/lista','ProductoController@index')->name('productos.lista');

Route::resource('usuario','UsuarioController');
Route::get('/usuarios/lista','UsuarioController@index')->name('usuarios.lista');

Route::resource('registroEntrada','RegistroEntradaController');
Route::get('/registroentradas/lista','RegistroEntradaController@index')->name('registroentradas.lista');

Route::resource('registroSalida','RegistroSalidaController');
Route::get('/registrosalidas/lista','RegistroSalidaController@index')->name('registrosalidas.lista');

Route::get('/kardex/lista','KardexController@index')->name('kardex.lista');

Route::resource('existencia','ExistenciaController');
Route::get('/inventario/lista','InventarioController@index')->name('inventario.lista');
Route::get('/inventario/{almacen}','InventarioController@detalle');
Route::get('/inventario/exportar/{almacen}','InventarioController@exportar');

Route::get('/kardex/exportar/{lista}','KardexController@exportar');

Route::resource('documento','DocumentoController');
Route::resource('disposicion','DisposicionController');

Route::get('/login','LoginController@index')->name('login');
Route::post('/loginprocess','LoginController@validar')->name('logueo');
Route::get('/logout','LoginController@logout')->name('logout');
Route::get('/loginprocess','LoginController@index');

Route::resource('ticket','TicketController');
Route::get('/tickets/lista','TicketController@index')->name('tickets.lista');
Route::get('/ticketNotificado/{idnotificacion}','TicketController@showTicketNotificado');
Route::put('/ticketNotificado/{idnotificacion}','TicketController@updateTicketNotificado');

Route::get('/acercade/mostrar','HomeController@mostrar')->name('acercade.mostrar');
#Auth::routes();

app/Almacen.php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model;

class Almacen extends Model
{

    protected $primaryKey = 'idalmacen';

    public function tipo(){
        return $this->belongsTo('App\Tipo','idtipo','idtipo');
    }
}

app/Http/Controllers/AlmacenController.php
<?php

namespace App\Http\Controllers;

use App\Almacen;
use App\RegistroEntrada;
use App\RegistroSalida;
use App\Tipo;
use App\Secuencia;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;


class AlmacenController extends Controller
{
    public function __construct()
    {
        #VALIDAR QUE EL USUARIO ESTE AUTENTICADO
        $this->middleware('auth');
    }

    public function index()
    {
        #SE VALIDA EL ROL AUTORIZADO
        Auth::user()->authorizeRoles(['ALMACEN']);

        $almacenes=Almacen::paginate(10);
        return view('almacen.lista-almacen',compact('almacenes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        #SE VALIDA EL ROL AUTORIZADO
        Auth::user()->authorizeRoles(['ALMACEN']);
        $tipos=Tipo::all();
        return view('almacen.crear-almacen',compact('tipos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        #SE VALIDA EL ROL AUTORIZADO
        Auth::user()->authorizeRoles(['ALMACEN']);

        $descripcion=$request->get('txtDescripcion');
        $idtipo=$request->get('txtTipo');

        #SI YA EXISTE UN ALMACEN , SE ENCUENTRA DUPLICADO
        $almacenBuscado=Almacen::where('descripcion','=',$descripcion)->first();
        if($almacenBuscado!=null){
            return back()->withErrors('El almacen '.$descripcion." ya EXISTE, ingrese un nombre de almacen diferente");
        }

        $almacen=new Almacen();
        $almacen->idalmacen=Secuencia::nextid();
        $almacen->descripcion=$descripcion;
        $almacen->idtipo=(int)$idtipo;
        $almacen->save();

        return redirect()->route('almacenes.lista');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Almacen  $almacen
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        #SE VALIDA EL ROL AUTORIZADO
        Auth::user()->authorizeRoles(['ALMACEN']);

        $almacen=Almacen::find((int)$id);
        return view('almacen.eliminar-almacen',compact('almacen'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Almacen  $almacen
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        #SE VALIDA EL ROL AUTORIZADO
        Auth::user()->authorizeRoles(['ALMACEN']);

        $tipos=Tipo::all();
        $almacen=Almacen::find((int)$id);
        return view('almacen.editar-almacen',compact('almacen'),compact('tipos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Almacen  $almacen
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        #SE VALIDA EL ROL AUTORIZADO
        Auth::user()->authorizeRoles(['ALMACEN']);

        $descripcion=$request->get('txtDescripcion');
        $idtipo=$request->get('txtTipo');

        $almacenBuscado=Almacen::find((int)$id);
        $almacenBuscado->descripcion=$descripcion;
        $almacenBuscado->idtipo=(int)$idtipo;
        $almacenBuscado->update();

        return redirect()->route('almacenes.lista');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Almacen  $almacen
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        #SE VALIDA EL ROL AUTORIZADO
        Auth::user()->authorizeRoles(['ALMACEN']);
        $almacenBuscado=Almacen::find((int)$id);

        $entradas=RegistroEntrada::where('idalmacen','=',(int)$id)->get();
        if(count($entradas)>0){
            return back()->withErrors('El almacen '.$almacenBuscado->descripcion." tiene ingresos, imposible eliminar");
        }

        $salidas=RegistroSalida::where('idalmacen','=',(int)$id)->get();
        if(count($salidas)>0){
            return back()->withErrors('El almacen '.$almacenBuscado->descripcion." tiene salidas, imposible eliminar");
        }




        $almacenBuscado->delete();

        return redirect()->route('almacenes.lista');
    }


}

resources/views/almacen/crear-almacen.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 subtitulo">
                Mantenimiento de Almacenes
            </div>
        </div>
    </div>


    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-2">
            </div>

            <div class="col-md-6 col-sm-12">
                <form class="needs-validation"  action="{{action('AlmacenController@store')}}" method="post" enctype="multipart/form-data" novalidate>
                    @csrf
                    <fieldset>
                        <legend class="sumario">Nuevo Almacen</legend>
                        @if(count($errors)>0)
                        <!-- SI HUBIERA ERRORES SE MUESTRA UNA LISTA CON LOS ERRORES ENCONTRADOS   -->
                            <div class="alert alert-danger">
                                <ul><!--SE REALIZA UN BUCLE PARA MOSTRAR LOS ERRORES -->
                                    @foreach($errors->all() as $error)
                                        <li>{{$error}}</li><!-- SE MUESTRA EL ERROR  -->
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <div class="form-group margenes-input">
                            <label for="txtDescripcion">Descripcion</label>
                            <input type="text" class="form-control" id="txtDescripcion" name="txtDescripcion"  placeholder="Ingrese una Descripcion" required autofocus maxlength="50">
                            <div class="invalid-feedback">
                                Por favor ingrese una Descripcion con 50 caracteres como máximo.
                            </div>
                        </div>

                        <div class="form-group margenes-input">
                            <label for="txtTipo">Tipo</label>
                            <select class="form-control btn-light" id="txtTipo" name="txtTipo" >
                                @foreach($tipos as $tipo)
                                    <option value={{$tipo->idtipo}}>{{$tipo->descripcion}} </option>
                                @endforeach
                            </select>
                            <div class="invalid-feedback">
                                Por favor seleccione un tipo.
                            </div>
                        </div>

                        <!-- SI EL ROL TIENE PERMISOS PARA EDITAR -->
                        <button type="submit" class="btn btn-success">Registrar <i class="fas fa-save iconoBoton"></i></button>

                        <button type="button" class="btn btn-secondary float-right" onclick="window.location='{{ route("almacenes.lista") }}'">Cancelar <i class="fas fa-undo-alt iconoBoton"></i></button>
                    </fieldset>
                </form>
            </div>

            <div class="col-md-2">
            </div>
        </div>
    </div>


@endsection

resources/views/almacen/editar-almacen.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 subtitulo">
                Mantenimiento de Almacenes
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-2">
            </div>

            <div class="col-md-6 col-sm-12">
                <form class="needs-validation"  action="{{action('AlmacenController@update',$almacen->idalmacen)}}" method="post" enctype="multipart/form-data" novalidate>
                    @csrf
                    {{ method_field('PUT') }}
                    <fieldset>
                        <legend class="sumario">Editar Almacen</legend>
                        @if(count($errors)>0)
                        <!-- SI HUBIERA ERRORES SE MUESTRA UNA LISTA CON LOS ERRORES ENCONTRADOS   -->
                            <div class="alert alert-danger">
                                <ul><!--SE REALIZA UN BUCLE PARA MOSTRAR LOS ERRORES -->
                                    @foreach($errors->all() as $error)
                                        <li>{{$error}}</li><!-- SE MUESTRA EL ERROR  -->
                                    @endforeach
                                </ul>
                            </div>
                        @endif


                        <div class="form-group ">
                            <label for="txtDescripcion">Descripcion</label>
                            <input type="text" class="form-control " id="txtDescripcion" name="txtDescripcion"
                                   value="{{$almacen->descripcion}}" placeholder="Ingrese una Descripcion" required autofocus maxlength="50">
                            <div class="invalid-feedback">
                                Por favor ingrese una descripcion con 50 caracteres como máximo.
                            </div>
                        </div>

                        <div class="form-group ">
                            <label for="txtTipo">Tipo</label>
                            <select class="form-control btn-light " id="txtTipo" name="txtTipo" >
                                @foreach($tipos as $tipo)

                                    @if($tipo->idtipo==$almacen->idtipo)
                                        <option value={{$tipo->idtipo}} selected>{{$tipo->descripcion}} </option>
                                    @else
                                        <option value={{$tipo->idtipo}}>{{$tipo->descripcion}} </option>
                                    @endif


                                @endforeach
                            </select>
                            <div class="invalid-feedback">
                                Por favor seleccione un tipo.
                            </div>
                        </div>

                        <!-- SI EL ROL TIENE PERMISOS PARA EDITAR -->
                        <button type="submit" class="btn btn-warning">Actualizar <i class="fas fa-save iconoBoton"></i></button>

                        <button type="button" class="btn btn-secondary float-right" onclick="window.location='{{ route("almacenes.lista") }}'">Cancelar <i class="fas fa-undo-alt iconoBoton"></i></button>
                    </fieldset>
                </form>
            </div>

            <div class="col-md-2">
            </div>
        </div>
    </div>


@endsection

resources/views/almacen/eliminar-almacen.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 subtitulo">
                Mantenimiento de Almacenes
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-2">
            </div>

            <div class="col-md-6 col-sm-12">
                <form class="needs-validation"  action="{{action('AlmacenController@destroy',$almacen->idalmacen)}}" method="post" enctype="multipart/form-data" novalidate>
                    @csrf
                    @method('DELETE')
                    <fieldset>
                        <legend class="sumario">Eliminar Almacen</legend>
                        @if(count($errors)>0)
                        <!-- SI HUBIERA ERRORES SE MUESTRA UNA LISTA CON LOS ERRORES ENCONTRADOS   -->
                            <div class="alert alert-danger">
                                <ul><!--SE REALIZA UN BUCLE PARA MOSTRAR LOS ERRORES -->
                                    @foreach($errors->all() as $error)
                                        <li>{{$error}}</li><!-- SE MUESTRA EL ERROR  -->
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <div class="form-group ">
                            <label for="txtDescripcion">Descripcion</label>
                            <input type="text" class="form-control" id="txtDescripcion" name="txtDescripcion"
                                   value="{{$almacen->descripcion}}" readonly   >
                            <div class="invalid-feedback">
                                Por favor ingrese una descripcion.
                            </div>
                        </div>

                        <div class="form-group ">
                            <label for="txtTipo">Tipo</label>
                            <input type="text" class="form-control" id="txtTipo" name="txtTipo"
                                   value="{{$almacen->tipo->descripcion}}" readonly   >

                            <div class="invalid-feedback">
                                Por favor seleccione un tipo.
                            </div>
                        </div>

                        <!-- SI EL ROL TIENE PERMISOS PARA EDITAR -->
                        <button type="submit" class="btn btn-danger">Eliminar <i class="fas fa-trash-alt IconColorRojo"></i></button>

                        <button type="button" class="btn btn-secondary float-right" onclick="window.location='{{ route("almacenes.lista") }}'">Cancelar <i class="fas fa-undo-alt iconoBoton"></i></button>
                    </fieldset>
                </form>
            </div>

            <div class="col-md-2">
            </div>
        </div>
    </div>


@endsection

resources/views/almacen/lista-almacen.blade.php
@extends('layouts.app')

@section('content')

    <div class="container-fluid">
        <div class="row justify-content-center align-items-center">
            <div class="col-3"></div>
            <div class="col-6 subtitulo Titulos">
                MANTENIMIENTO DE ALMACENES
            </div>

            <div class="col-3">
                    <!-- SI EL ROL TIENE PERMISOS PARA EDITAR -->
                    <a class="btn btn-success" href="{{route('almacen.create')}}">
                        Crear <i class="fas fa-file-alt"></i>
                    </a>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <table class="table">
                    <thead class="thead thead-light">
                        <tr>
                            <th scope="col">DESCRIPCION</th>
                            <th scope="col">TIPO</th>
                            <th scope="col">ACCIONES</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($almacenes as $almacen)
                            <tr>
                                <td>{{$almacen->descripcion}}</td>
                                <td>{{$almacen->tipo->descripcion}}</td>

                                <td>
                                    <a class="btn btn-warning" href="{{action('AlmacenController@edit',$almacen->idalmacen)}}">
                                        Editar <i class="fas fa-pencil-alt"></i>
                                    </a>

                                    <a class="btn btn-danger" href="{{action('AlmacenController@show',$almacen->idalmacen)}}">
                                       Eliminar <i class="fas fa-trash-alt"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                <div class="row">
                    <div class="mx-auto">
                        {{$almacenes->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection